"""Projects Module - Handles project creation and management"""

import os
from modules.voice import speak
from modules.ai import generate_game_code
import subprocess


def create_python_project(project_name):
    """Create a Python project with folder structure"""
    try:
        # Create main project folder
        os.makedirs(project_name, exist_ok=True)
        os.chdir(project_name)
        
        # Create folder structure
        os.makedirs("src", exist_ok=True)
        os.makedirs("tests", exist_ok=True)
        os.makedirs("data", exist_ok=True)
        
        # Create main.py
        with open("src/main.py", "w") as f:
            f.write("""# Main Python Project File
def main():
    print("Hello, World!")

if __name__ == "__main__":
    main()
""")
        
        # Create requirements.txt
        with open("requirements.txt", "w") as f:
            f.write("# Add your project dependencies here\n")
        
        # Create README.md
        with open("README.md", "w") as f:
            f.write(f"# {project_name}\n\nThis is a Python project.\n")
        
        # Create .gitignore
        with open(".gitignore", "w") as f:
            f.write("__pycache__/\n*.py[cod]\n*$py.class\n*.so\n.venv/\nvenv/\nenv/\n")
        
        os.chdir("..")
        speak(f"Python project {project_name} created successfully")
        return True
    except Exception as e:
        speak(f"Error creating project: {e}")
        return False


def create_game_project(project_name, game_type):
    """Create a complete game project with code generated by AI"""
    try:
        os.makedirs(project_name, exist_ok=True)
        os.chdir(project_name)
        
        # Create folder structure
        os.makedirs("src", exist_ok=True)
        os.makedirs("assets", exist_ok=True)
        os.makedirs("assets/images", exist_ok=True)
        os.makedirs("assets/sounds", exist_ok=True)
        
        speak(f"Generating {game_type} game code. This may take a moment...")
        
        # Generate game code using AI
        game_code = generate_game_code(project_name, game_type)
        
        if not game_code:
            os.chdir("..")
            speak("Failed to generate game code")
            return False
        
        # Create main game file
        with open("src/main.py", "w") as f:
            f.write(game_code)
        
        # Create requirements.txt with pygame
        with open("requirements.txt", "w") as f:
            f.write("pygame>=2.0.0\n")
        
        # Create README.md
        with open("README.md", "w") as f:
            f.write(f"""# {project_name}

A {game_type} game created with Python and Pygame.

## Installation

```bash
pip install -r requirements.txt
```

## Running the Game

```bash
python src/main.py
```

## Game Controls

Use arrow keys or WASD to move.
Space or Click to interact.

## Features

- Smooth gameplay
- Collision detection
- Score system
- Game over screen

Enjoy!
""")
        
        # Create .gitignore
        with open(".gitignore", "w") as f:
            f.write("__pycache__/\n*.py[cod]\n*$py.class\n*.so\n.venv/\nvenv/\nenv/\n")
        
        os.chdir("..")
        speak(f"Complete {game_type} game project {project_name} created successfully")
        return True
    except Exception as e:
        speak(f"Error creating game project: {e}")
        return False


def create_web_project(project_name):
    """Create a Web project with HTML, CSS, JS structure"""
    try:
        os.makedirs(project_name, exist_ok=True)
        os.chdir(project_name)
        
        # Create folder structure
        os.makedirs("css", exist_ok=True)
        os.makedirs("js", exist_ok=True)
        os.makedirs("images", exist_ok=True)
        
        # Create index.html
        with open("index.html", "w") as f:
            f.write("""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome</title>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <h1>Welcome to Web Project</h1>
    <script src="js/main.js"></script>
</body>
</html>
""")
        
        # Create CSS
        with open("css/style.css", "w") as f:
            f.write("""body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 20px;
    background-color: #f0f0f0;
}

h1 {
    color: #333;
}
""")
        
        # Create JavaScript
        with open("js/main.js", "w") as f:
            f.write("""console.log('Web project loaded!');
""")
        
        # Create README.md
        with open("README.md", "w") as f:
            f.write(f"# {project_name}\n\nThis is a Web project.\n")
        
        os.chdir("..")
        speak(f"Web project {project_name} created successfully")
        return True
    except Exception as e:
        speak(f"Error creating project: {e}")
        return False


def open_vscode_project(project_path):
    """Open VS Code in the project directory"""
    try:
        subprocess.Popen(["code", project_path])
        speak(f"Opening VS Code for {project_path}")
        return True
    except Exception as e:
        speak(f"Error opening VS Code: {e}")
        return False
