from openai import OpenAI
import speech_recognition as sr
import pyttsx3
import pyautogui
import webbrowser
import os
from dotenv import load_dotenv
import sounddevice as sd
import soundfile as sf
import numpy as np
from comtypes.client import CreateObject
import time
import subprocess
import shutil

load_dotenv()

# ===================== CONFIG =====================
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")

if not OPENAI_API_KEY:
    print("Error: OPENAI_API_KEY environment variable is not set!")
    print("Please add your API key to the .env file")
    exit(1)

client = OpenAI(api_key=OPENAI_API_KEY)

# Use Windows SAPI5 directly via comtypes
try:
    speaker = CreateObject("SAPI.SpVoice")
except Exception as e:
    print(f"Warning: Could not initialize SAPI speaker: {e}")
    speaker = None

recognizer = sr.Recognizer()

# ===================== SPEAK =====================
def speak(text):
    print("Sam:", text)
    try:
        if speaker:
            # Use SAPI5 directly
            speaker.Speak(text, 0)
            time.sleep(0.5)  # Give it time to speak
        else:
            # Fallback to pyttsx3
            engine = pyttsx3.init('sapi5')
            engine.setProperty('rate', 150)
            engine.setProperty('volume', 1.0)
            engine.say(text)
            engine.runAndWait()
    except Exception as e:
        print(f"Voice error: {e}")

# LISTEN
def listen():
    try:
       
        print("Listening...")
        duration = 5 
        sample_rate = 16000
        audio_data = sd.rec(int(duration * sample_rate), samplerate=sample_rate, channels=1, dtype='int16')
        sd.wait()
        
        
        from io import BytesIO
        audio_bytes = audio_data.tobytes()
        audio = sr.AudioData(audio_bytes, sample_rate, 2)
        
        try:
            text = recognizer.recognize_google(audio)
            print("You:", text)
            return text
        except sr.UnknownValueError:
            print("Sorry, I didn't catch that. Please try again.")
            return ""
        except sr.RequestError:
            print("Error with the speech recognition service.")
            return ""
    except Exception as e:
        print(f"Microphone error: {e}")
        return ""

# OPENAI
def ask_openai(prompt):
    response = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "system", "content": "You are Sam, a smart AI assistant that can control the computer."},
            {"role": "user", "content": prompt}
        ]
    )
    return response.choices[0].message.content

# ===================== PROJECT CREATION =====================
def create_python_project(project_name):
    """Create a Python project with folder structure"""
    try:
        # Create main project folder
        os.makedirs(project_name, exist_ok=True)
        os.chdir(project_name)
        
        # Create folder structure
        os.makedirs("src", exist_ok=True)
        os.makedirs("tests", exist_ok=True)
        os.makedirs("data", exist_ok=True)
        
        # Create main.py
        with open("src/main.py", "w") as f:
            f.write("""# Main Python Project File
def main():
    print("Hello, World!")

if __name__ == "__main__":
    main()
""")
        
        # Create requirements.txt
        with open("requirements.txt", "w") as f:
            f.write("# Add your project dependencies here\n")
        
        # Create README.md
        with open("README.md", "w") as f:
            f.write(f"# {project_name}\n\nThis is a Python project.\n")
        
        # Create .gitignore
        with open(".gitignore", "w") as f:
            f.write("__pycache__/\n*.py[cod]\n*$py.class\n*.so\n.venv/\nvenv/\nenv/\n")
        
        os.chdir("..")
        speak(f"Python project {project_name} created successfully")
        return True
    except Exception as e:
        speak(f"Error creating project: {e}")
        return False

def create_game_project(project_name, game_type):
    """Create a complete game project with code generated by AI"""
    try:
        os.makedirs(project_name, exist_ok=True)
        os.chdir(project_name)
        
        # Create folder structure
        os.makedirs("src", exist_ok=True)
        os.makedirs("assets", exist_ok=True)
        os.makedirs("assets/images", exist_ok=True)
        os.makedirs("assets/sounds", exist_ok=True)
        
        speak(f"Generating {game_type} game code. This may take a moment...")
        
        # Use OpenAI to generate game code
        prompt = f"""Create a complete Python {game_type} game using pygame. 
        Project name: {project_name}
        
        Generate clean, well-commented code with:
        1. Main game class
        2. Game loop
        3. Collision detection
        4. Score system
        5. Game over screen
        
        Make it fun and playable. Return only the Python code, no explanations."""
        
        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": "You are an expert Python game developer. Generate complete, working game code."},
                {"role": "user", "content": prompt}
            ]
        )
        
        game_code = response.choices[0].message.content
        
        # Clean up code if it has markdown markers
        if "```python" in game_code:
            game_code = game_code.split("```python")[1].split("```")[0]
        elif "```" in game_code:
            game_code = game_code.split("```")[1].split("```")[0]
        
        # Create main game file
        with open("src/main.py", "w") as f:
            f.write(game_code)
        
        # Create requirements.txt with pygame
        with open("requirements.txt", "w") as f:
            f.write("pygame>=2.0.0\n")
        
        # Create README.md
        with open("README.md", "w") as f:
            f.write(f"""# {project_name}

A {game_type} game created with Python and Pygame.

## Installation

```bash
pip install -r requirements.txt
```

## Running the Game

```bash
python src/main.py
```

## Game Controls

Use arrow keys or WASD to move.
Space or Click to interact.

## Features

- Smooth gameplay
- Collision detection
- Score system
- Game over screen

Enjoy!
""")
        
        # Create .gitignore
        with open(".gitignore", "w") as f:
            f.write("__pycache__/\n*.py[cod]\n*$py.class\n*.so\n.venv/\nvenv/\nenv/\n")
        
        os.chdir("..")
        speak(f"Complete {game_type} game project {project_name} created successfully")
        return True
    except Exception as e:
        speak(f"Error creating game project: {e}")
        return False

def create_web_project(project_name):
    """Create a Web project with HTML, CSS, JS structure"""
    try:
        os.makedirs(project_name, exist_ok=True)
        os.chdir(project_name)
        
        # Create folder structure
        os.makedirs("css", exist_ok=True)
        os.makedirs("js", exist_ok=True)
        os.makedirs("images", exist_ok=True)
        
        # Create index.html
        with open("index.html", "w") as f:
            f.write("""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome</title>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <h1>Welcome to Web Project</h1>
    <script src="js/main.js"></script>
</body>
</html>
""")
        
        # Create CSS
        with open("css/style.css", "w") as f:
            f.write("""body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 20px;
    background-color: #f0f0f0;
}

h1 {
    color: #333;
}
""")
        
        # Create JavaScript
        with open("js/main.js", "w") as f:
            f.write("""console.log('Web project loaded!');
""")
        
        # Create README.md
        with open("README.md", "w") as f:
            f.write(f"# {project_name}\n\nThis is a Web project.\n")
        
        os.chdir("..")
        speak(f"Web project {project_name} created successfully")
        return True
    except Exception as e:
        speak(f"Error creating project: {e}")
        return False

def open_vscode_project(project_path):
    """Open VS Code in the project directory"""
    try:
        subprocess.Popen(["code", project_path])
        speak(f"Opening VS Code for {project_path}")
        return True
    except Exception as e:
        speak(f"Error opening VS Code: {e}")
        return False

# OPENAI
def ask_openai(prompt):
    response = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "system", "content": "You are Sam, a smart AI assistant that can control the computer."},
            {"role": "user", "content": prompt}
        ]
    )
    return response.choices[0].message.content

# COMMANDS 
def handle_command(command):
    cmd = command.lower()

    if "exit" in cmd or "quit" in cmd or "terminate" in cmd or "stop" in cmd:
        speak("Goodbye!")
        exit(0)

    elif "create python project" in cmd:
        # Extract project name
        project_name = cmd.replace("create python project", "").replace("called", "").replace("named", "").strip()
        if not project_name:
            speak("Please provide a project name")
            return
        project_name = project_name.split()[0] if project_name else "my_project"
        create_python_project(project_name)
        open_vscode_project(project_name)

    elif "create game project" in cmd or "develop game" in cmd or "create game" in cmd:
        # Extract game type and project name
        parts = cmd.replace("create game project", "").replace("develop game", "").replace("create game", "").strip()
        words = parts.split()
        
        if len(words) >= 2:
            game_type = words[0]  # e.g., "flappy" or "snake"
            project_name = words[1]  # e.g., "bird" or "game"
        elif len(words) == 1:
            game_type = words[0]
            project_name = f"{game_type}_game"
        else:
            speak("Please specify a game type and project name")
            return
        
        create_game_project(project_name, game_type)
        open_vscode_project(project_name)

    elif "create web project" in cmd:
        # Extract project name
        project_name = cmd.replace("create web project", "").replace("called", "").replace("named", "").strip()
        if not project_name:
            speak("Please provide a project name")
            return
        project_name = project_name.split()[0] if project_name else "web_project"
        create_web_project(project_name)
        open_vscode_project(project_name)

    elif "open vscode" in cmd:
        subprocess.Popen(["code"])
        speak("Opening VS Code")

    elif "google" in cmd and ("search" in cmd or "find" in cmd):
        # Extract search query
        if "search for" in cmd:
            search_query = cmd.split("search for", 1)[1].strip()
        elif "find" in cmd:
            search_query = cmd.split("find", 1)[1].strip()
        else:
            search_query = cmd.replace("google", "").strip()
        
        # Remove extra words
        search_query = search_query.replace("on google", "").replace("google", "").strip()
        
        if search_query:
            speak(f"Searching for {search_query} on Google")
            webbrowser.open(f"https://www.google.com/search?q={search_query}")
        else:
            speak("Opening Google")
            webbrowser.open("https://google.com")

    elif "youtube" in cmd and ("search" in cmd or "find" in cmd):
        # Extract search query
        if "search for" in cmd:
            search_query = cmd.split("search for", 1)[1].strip()
        elif "find" in cmd:
            search_query = cmd.split("find", 1)[1].strip()
        else:
            search_query = cmd.replace("youtube", "").strip()
        
        # Remove extra words
        search_query = search_query.replace("on youtube", "").replace("youtube", "").strip()
        
        if search_query:
            speak(f"Searching for {search_query} on YouTube")
            webbrowser.open(f"https://www.youtube.com/results?search_query={search_query}")
        else:
            speak("Opening YouTube")
            webbrowser.open("https://youtube.com")

    elif "open google" in cmd:
        webbrowser.open("https://google.com")
        speak("Opening Google")

    elif "open youtube" in cmd:
        webbrowser.open("https://youtube.com")
        speak("Opening YouTube")

    elif "open notepad" in cmd:
        os.system("notepad")
        speak("Opening Notepad")

    elif "open calculator" in cmd:
        os.system("calc")
        speak("Opening Calculator")

    elif "open file explorer" in cmd or "open explorer" in cmd:
        os.system("explorer")
        speak("Opening File Explorer")

    elif "open command prompt" in cmd or "open cmd" in cmd:
        os.system("cmd")
        speak("Opening Command Prompt")

    elif "screenshot" in cmd or "take screenshot" in cmd:
        pyautogui.screenshot()
        speak("Screenshot taken")

    elif "lock screen" in cmd or "lock laptop" in cmd:
        os.system("rundll32.exe user32.dll,LockWorkStation")
        speak("Locking the screen")

    elif "sleep" in cmd or "go to sleep" in cmd:
        os.system("rundll32.exe powrprof.dll,SetSuspendState 0,1,0")
        speak("Putting laptop to sleep")

    elif "type" in cmd:
        text = cmd.replace("type", "")
        pyautogui.write(text)
        speak("Done typing")

    elif "shutdown" in cmd:
        speak("Shutting down in 5 seconds")
        os.system("shutdown /s /t 5")

    elif "restart" in cmd:
        speak("Restarting in 5 seconds")
        os.system("shutdown /r /t 5")

    else:
        reply = ask_openai(command)
        speak(reply)

def main():
    speak("Hello, I am Sam. How can I help you?")
    while True:
        command = listen()
        if command:
            handle_command(command)

if __name__ == "__main__":
    main()
